pipeline {
  agent any
  stages {
    stage('Test') {
      agent {
        docker {
          image 'gcc:latest'
        }

      }
      steps {
        sh 'git submodule update --init --recursive'
        sh 'cd client/tests; make test'
      }
    }

  }
}
